version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: inventario_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inventario_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: